### ISSUE TITLE
[Global] : gestion des typographie

### ISSUE THREAD

**Issue by moreaupierrick** [moreaupierrick/OpenDoCSS#1]
Objectif : 
- gestion des typographie avec de nouvelle classe propre à OpenDoCSS
- surcharge css des composants html(h1,h2,h3,h4, small, strong, u, em, a ...)

**Comment by mikaSez** [comment]
Il faudrait réfléchir sur les composants, mais je ne vois pas grand intérê pour continuer sur les composants généraux. 
Il faudrait regarder plutôt du côté des classes .
